version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: server
    main: ./cmd/server
    binary: goshort
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

  - id: cli
    main: ./cmd/cli
    binary: goshort-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: server
    ids: [server]
    name_template: "goshort_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

  - id: cli
    ids: [cli]
    name_template: "goshort-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

dockers:
  - image_templates:
      - "ghcr.io/anicedantfa/goshort:{{ .Tag }}"
      - "ghcr.io/anicedantfa/goshort:latest"
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - docs/openapi.yaml
    ids:
      - server
    build_flag_templates:
      - "--platform=linux/amd64"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^📝 docs"
      - "^🔨 chore"
      - "^💄 style"
      - "^ci:"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: "✨ New Features"
      regexp: "^.*✨ feat.*$"
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: "^.*🐛 fix.*$"
      order: 1
    - title: "♻️ Refactors"
      regexp: "^.*♻️ refactor.*$"
      order: 2
    - title: "⚡️ Performance"
      regexp: "^.*⚡️ perf.*$"
      order: 3
    - title: "🔧 Configuration"
      regexp: "^.*🔧 configs.*$"
      order: 4
    - title: "✅ Tests"
      regexp: "^.*✅ test.*$"
      order: 5
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: anIcedAntFA
    name: goshort
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
