// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Counter struct {
	ID    int64
	Value int64
}

type Url struct {
	ID          int64
	ShortCode   string
	OriginalUrl string
	IsCustom    int64
	CreatedAt   string
	ExpiresAt   sql.NullString
	ClickCount  int64
	Title       string
	Description string
}
