// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const countURLs = `-- name: CountURLs :one
SELECT COUNT(*) FROM urls
`

func (q *Queries) CountURLs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countURLs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createURL = `-- name: CreateURL :one
INSERT INTO urls (short_code, original_url, is_custom, expires_at, title, description)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, short_code, original_url, is_custom, created_at, expires_at, click_count, title, description
`

type CreateURLParams struct {
	ShortCode   string
	OriginalUrl string
	IsCustom    int64
	ExpiresAt   sql.NullString
	Title       string
	Description string
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createURL,
		arg.ShortCode,
		arg.OriginalUrl,
		arg.IsCustom,
		arg.ExpiresAt,
		arg.Title,
		arg.Description,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.IsCustom,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClickCount,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const deleteByCode = `-- name: DeleteByCode :execrows
DELETE FROM urls WHERE short_code = ?
`

func (q *Queries) DeleteByCode(ctx context.Context, shortCode string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteByCode, shortCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpired = `-- name: DeleteExpired :execrows
DELETE FROM urls WHERE id IN (
    SELECT id FROM urls
    WHERE expires_at IS NOT NULL AND expires_at < datetime('now')
    LIMIT ?
)
`

func (q *Queries) DeleteExpired(ctx context.Context, limit int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpired, limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getByCode = `-- name: GetByCode :one
SELECT id, short_code, original_url, is_custom, created_at, expires_at, click_count, title, description FROM urls WHERE short_code = ?
`

func (q *Queries) GetByCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getByCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.IsCustom,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClickCount,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const getCounter = `-- name: GetCounter :one
SELECT value FROM counter WHERE id = 1
`

func (q *Queries) GetCounter(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCounter)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const incrementClicks = `-- name: IncrementClicks :exec
UPDATE urls SET click_count = click_count + 1 WHERE short_code = ?
`

func (q *Queries) IncrementClicks(ctx context.Context, shortCode string) error {
	_, err := q.db.ExecContext(ctx, incrementClicks, shortCode)
	return err
}

const incrementCounter = `-- name: IncrementCounter :one
UPDATE counter SET value = value + 1 WHERE id = 1 RETURNING value
`

func (q *Queries) IncrementCounter(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, incrementCounter)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const listURLs = `-- name: ListURLs :many
SELECT id, short_code, original_url, is_custom, created_at, expires_at, click_count, title, description FROM urls ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListURLsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListURLs(ctx context.Context, arg ListURLsParams) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, listURLs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Url{}
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.ShortCode,
			&i.OriginalUrl,
			&i.IsCustom,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ClickCount,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMetadata = `-- name: UpdateMetadata :one
UPDATE urls SET title = ?, description = ? WHERE short_code = ? RETURNING id, short_code, original_url, is_custom, created_at, expires_at, click_count, title, description
`

type UpdateMetadataParams struct {
	Title       string
	Description string
	ShortCode   string
}

func (q *Queries) UpdateMetadata(ctx context.Context, arg UpdateMetadataParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, updateMetadata, arg.Title, arg.Description, arg.ShortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.IsCustom,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClickCount,
		&i.Title,
		&i.Description,
	)
	return i, err
}
